export { Edu } from "./Edu"
export { Header } from "./Header"
export { Hero } from "./Hero"
export { Services } from "./Services"
export { Team } from "./Team"
export { Work } from "./Work"
export { Testimonial } from "./Testimonial"
export { Contact } from "./Contact"
